[package]
name = "fastcgi-client"
version = "0.5.0"
authors = ["__JM_Joy__ <918734043@qq.com>"]
edition = "2018"
description = "Fastcgi client implemented for Rust."
repository = "https://github.com/jmjoy/fastcgi-client-rs"
license = "MIT"
readme = "README.md"
keywords = ["fastcgi", "fastcgi-client", "php", "php-fpm", "futures", "async-std"]
exclude = [
    "fastcgi-client-rs.png",
    ".gitignore",
    ".travis.yml",
    "rustfmt.toml"
]

[dependencies]
bufstream = "0.1.4"
byteorder = "1.3.1"
error-chain = "0.12.1"
futures = {version = "0.3", optional = true}
log = "0.4.6"

[dev-dependencies]
async-std = {version = "1.0.1", features = ["attributes"]}
env_logger = "0.6.1"

[features]
default = ["futures"]
