[package]
name = "fastcgi-client"
version = "0.6.2"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
description = "Fastcgi client implemented for Rust."
repository = "https://github.com/jmjoy/fastcgi-client-rs"
license = "MIT"
readme = "README.md"
keywords = ["fastcgi", "fcgi", "client", "tokio", "php"]

[dependencies]
http = "0.2"
log = "0.4"
thiserror = "1"
tokio = { version = "1", features = ["io-util", "sync", "time"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
env_logger = "0.8"
