[package]
name = "fastcgi-client"
version = "0.2.0"
authors = ["__JM_Joy__ <918734043@qq.com>"]
edition = "2018"
description = "Fastcgi client implemented for Rust."
repository = "https://github.com/jmjoy/fastcgi-client-rs"
license = "MIT"
readme = "README.md"
keywords = ["fastcgi", "fastcgi-client", "php", "php-fpm"]

[dependencies]
byteorder = "1.3.1"
log = "0.4.6"
error-chain = "0.12.1"

[dev-dependencies]
env_logger = "0.6.1"

